number: 
last_name: 
first_name: 
middle_name: 
extension_name: 
birth_date: 
relationship: 
sex: 
relationship: 
place_of_birth: 
citizenship: 
civil_status: 
status_of_residency: 
religion: 
dialect: 
ethnic_group: 
schooling: 
highest_educational_attainment: 
means_of_transportation: 
blood_type: 
registered_voter: 
national_id: 
philhealth: 
sss_id: 
bir_id: 
mobile_number: 
solo_parent: 
disablity: 
senior_citizen: 
family_planning: 
4ps_member: 
pregnant_or_breastfeeding: 
address: 
status_of_house_ownership_lot_and_house: 
type_of_dwelling: 
lightning_source: 
source_of_water: 
water_disposal: 
garbage_disposal: 
beneficiary_of: 
pets: 
vaccinated: 
main_source_of_information_in_household: 
car_vehicle: 
garage: 
color: 
plate_number: 
employment_information: 
for_age_0_to_6_years_old: 